//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Reserve
    {
        public int id { get; set; }
        public int book_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime reserve_on { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
