//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Lend
    {
        public int id { get; set; }
        public int book_id { get; set; }
        public string user_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public Nullable<System.DateTime> extended_date { get; set; }
        public int returned { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Book Book { get; set; }
    }
}
